name: GitHub Actions CI/CD

# 觸發action的時機
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  # 可以手動執行此 action

jobs:
  anime_crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9.18"
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Python File
        run: |
          python static.py
          python api.py
      - name: Commit Data To GitHub Repo  
        run: |
          git config --global user.name "bot"
          git config --global user.email "xiangwei0131@gmail.com"
          git add static.json && git commit -m "Update static.json by bot"
          git add api.csv && git commit -m "Update api.csv by bot"
          git push origin main